name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialise repo
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "radiocc/doc"

    - name: Postprocess build
      run: |
        chmod +x postprocess-build.sh
        postprocess-build.sh 

    - name: Isolate build folder to be in separate branch
      run: |
        # cd build
        cd radiocc/doc/build
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Push it
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
        branch: build
        force: true
        # directory: ./build
        directory: ./radiocc/doc/build
