name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialise repo
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "radiocc/doc"

    - name: Postprocess build
      run: |
        sudo chmod +x ./postprocess-build.sh
        sudo ./postprocess-build.sh 

    - name: radiocc/doc/build is the new root (for the webpage)
      run: 
        git add radiocc/doc/build
        git commit -m "deploy"
        git subtree push --prefix radiocc/doc/build origin gh-pages
