name: Deploy to GitHub pages
on: 
  issue_comment:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.issue.number == '2'
        && github.event.issue.user.login == 'GregoireHENRY'
        && github.event.comment.body == 'Bro can you update? 🎠' }}
    steps:
    - name: Initialise repo
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "radiocc/doc"

    - name: Postprocess build
      run: |
        sudo chmod +x ./postprocess-build.sh
        sudo ./postprocess-build.sh 

    - name: Isolate build folder to be in separate branch
      run: |
        sudo chown -R $USER:$USER radiocc/doc/build
        cd radiocc/doc/build
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Push it
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
        branch: gh-pages
        force: true
        directory: ./radiocc/doc/build

    - name: Inform about build done
      env:
        TOKEN: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $TOKEN" "https://api.github.com/repos/GregoireHENRY/radiocc-doc-website/issues/2/comments" -d "{\"body\":\"Gotcha! 🤖🪄 ✨\"}"
