name: On issue comment

on: 
  issue_comment:
    types: created

jobs:
  check_comment:
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
      COMMENT: ${{ github.event.comment.body }}
      CHECK: ${{ github.event.issue.number == '1'
        && github.event.issue.user.login == 'GregoireHENRY'
        && github.event.comment.body == 'Plz do dat build' }}
    steps:
      - id: export
        name: Detect magic comment
        run: echo "::set-output name=check::${CHECK}"
    outputs:
      check: ${{ steps.export.outputs.check }}

  update_module:
    runs-on: ubuntu-latest
    needs: check_comment
    if: ${{ needs.check_comment.outputs.check == true }}
    steps:
      - uses: actions/checkout@v2
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto: update submodules" || echo "No changes to commit"
          git push
        
  docs:
    runs-on: ubuntu-latest
    needs: update_module
    if: ${{ needs.check_comment.outputs.check == true }}
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "radiocc/doc/"
    - uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: radiocc/doc/build/html/
