name: On issue comment

on: 
  issue_comment:
    types: created

jobs:
  check_comment:
    name: First issue commented by the boss with magic word
    if: |
      ${{ github.event.issue.number == "1"
      && github.event.issue.user.login == "GregoireHENRY"
      && github.event.comment.body == "Plz do dat build" }}$
    runs-on: ubuntu-latest
    steps:
    - name: Friendly accept 
      run: echo "Yo if ya ask it dat wey i'll do it huh"
