name: On issue comment

on: issue_comment
  types: created

jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "issue number : ${NUMBER}"
        echo "user login : ${USER_LOGIN}"
        echo "user id : ${USER_ID}"
        echo "comment : ${COMMENT}"
      env:
        NUMBER: ${{ github.event.issue.number }}
        USER_LOGIN: ${{ github.event.issue.user.login }}
        USER_ID: ${{ github.event.issue.user.id }}
        COMMENT: ${{ github.event.comment.body }}
