name: Sphinx build

#on:
# workflow_run:
#    workflows: ["Update module"]
#    types:
#      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "radiocc/doc/"
    - uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: radiocc/doc/build/html/
