name: Sphinx build

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Sumbodule Update
      run: |
          git submodule update --init --recursive
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx
          pydata-sphinx-theme
          sphinx-autoapi
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "radiocc/doc/"
    - uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: radiocc/doc/build/html/
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: radiocc/doc/build/html
