name: Update module

on:
  workflow_run:
    workflows: ["On issue comment"]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      repository: radiocc
      token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Commit
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add --all
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
